INSERT INTO GENEROS(NOMBRE) VALUES('ACCION');
INSERT INTO GENEROS(NOMBRE) VALUES('COMEDIA');
INSERT INTO GENEROS(NOMBRE) VALUES('DRAMA');
INSERT INTO GENEROS(NOMBRE) VALUES('FANTASIA');
INSERT INTO GENEROS(NOMBRE) VALUES('TERROR');

INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('HUGH JACKMAN', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbaKh93lbXDtBWeJOPpPeXX1iHSJmbnPCxopdu_qmqeNekTgme');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('KEANU REEVES', 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQMcj_F-fr3KsmiVNtshpjL2p6yfvv3WEjzjcM5tWMVkrrgyA6Z');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('MARGOT ROBBIE', 'https://media.gq.com.mx/photos/5ed6c25f799362c9dbb463e2/4:3/w_3372,h_2529,c_limit/GettyImages-512946906');


INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 1', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 2', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 3', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 4', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 5', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 6', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 7', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 8', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 9', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 10', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 11', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 12', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 13', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 14', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 15', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 16', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 17', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 18', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 19', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 20', 1, '2024-02-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test 21', 1, '2024-02-02');